### ISSUE TITLE
[IDEA] I think the controls should be changed to match Super Mario Galaxy

### ISSUE THREAD

**Issue by alvsz** [PGgamer2/sm64_wii#1]
Firstly, I don't know if this project is still in development so sorry if I am filling up your email inbox.

Z: Duck
B: Attack
C: Change camera mode

**Comment by PGgamer2** [comment]
Sorry for the late response.
I'm not updating the port anymore because I have other things to do and I had some troubles finding documentation.
Anyway you are right, it would make more sense to change the controls to Super Mario Galaxy ones.

**Comment by PGgamer2** [comment]
Ok I changed the controls with the [c2728c8](https://github.com/PGgamer2/sm64_wii/commit/c2728c8d6d4b1a60d62f4d1db5b78cedc8cceebe) commit.
